version : '3.7'

services:
  web:
    build: ./Shipment_Assignment
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./Shipment_Assignment:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev
    depends_on:
      - db


  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shipment_assignment
      - POSTGRES_PASSWORD=qwerty11
      - POSTGRES_DB=shipment

volumes:
  postgres_data: