# Generated by Django 3.0.2 on 2020-02-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20200203_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipmentReference',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField()),
                ('latestDeliveryDate', models.DateTimeField()),
                ('ean', models.IntegerField()),
                ('title', models.CharField(max_length=4096)),
                ('quantity', models.IntegerField()),
                ('offerPrice', models.FloatField()),
                ('offerCondition', models.CharField(max_length=1024)),
                ('fulfilmentMethod', models.CharField(max_length=1024)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shipment.Shipment')),
            ],
        ),
    ]
