# Generated by Django 3.0.2 on 2020-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20200203_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilmentMethod',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='offerCondition',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='offerPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderItemId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
